import {
  IndeedIcon,
  LinkedInIcon,
  ZipRecruiterIcon,
  MonsterIcon,
  GlassdoorIcon,
  Scan123Icon,
  WellskyIcon,
} from "@/components/platform-icons"
import type {
  AvailablePlatform,
  ApplicantTrendDatum,
  Candidate,
  IntegrationWorkflowStep,
  JobSource,
  PlatformIntegration,
  RecentActivity,
  SourceDistributionDatum,
} from "./types"

export const jobSources: JobSource[] = [
  { id: 1, name: "Indeed", icon: IndeedIcon, connected: true, applicants: 24, color: "bg-blue-500" },
  { id: 2, name: "Scan123", icon: Scan123Icon, connected: true, applicants: 18, color: "bg-purple-500" },
  { id: 3, name: "Wellsky", icon: WellskyIcon, connected: true, applicants: 12, color: "bg-teal-500" },
]

export const availablePlatforms: AvailablePlatform[] = [
  { id: 4, name: "LinkedIn", icon: LinkedInIcon, color: "bg-blue-600" },
  { id: 5, name: "ZipRecruiter", icon: ZipRecruiterIcon, color: "bg-green-500" },
  { id: 6, name: "Monster", icon: MonsterIcon, color: "bg-purple-600" },
  { id: 7, name: "Glassdoor", icon: GlassdoorIcon, color: "bg-emerald-500" },
]

export const applicantTrendData: ApplicantTrendDatum[] = [
  { month: "Jan", applicants: 45, interviews: 12, offers: 8 },
  { month: "Feb", applicants: 52, interviews: 15, offers: 10 },
  { month: "Mar", applicants: 48, interviews: 14, offers: 9 },
  { month: "Apr", applicants: 61, interviews: 18, offers: 12 },
  { month: "May", applicants: 55, interviews: 16, offers: 11 },
  { month: "Jun", applicants: 67, interviews: 20, offers: 15 },
]

export const sourceDistributionData: SourceDistributionDatum[] = [
  { name: "Indeed", value: 45, color: "#3b82f6" },
  { name: "Scan123", value: 30, color: "#a855f7" },
  { name: "Wellsky", value: 25, color: "#14b8a6" },
]

export const recentActivityData: RecentActivity[] = [
  { id: 1, candidate: "Amara Okafor", action: "Interview Scheduled", date: "2024-01-15", status: "Pending" },
  { id: 2, candidate: "Kwame Mensah", action: "Application Received", date: "2024-01-14", status: "New" },
  { id: 3, candidate: "Zainab Hassan", action: "Offer Sent", date: "2024-01-13", status: "Awaiting Response" },
  { id: 4, candidate: "John Doe", action: "Profile Reviewed", date: "2024-01-12", status: "In Progress" },
  { id: 5, candidate: "Jane Smith", action: "Background Check", date: "2024-01-11", status: "Verified" },
]

export const applicants: Candidate[] = [
  {
    id: 1,
    name: "Amara Okafor",
    role: "Registered Nurse",
    location: "Lagos, Nigeria",
    trustScore: 98,
    skills: ["Pediatric Care", "Emergency Response", "Patient Education"],
    allergySafe: true,
    matchScore: 95,
    avatar: "/african-woman-nurse.jpg",
    phone: "+234 801 234 5678",
    email: "amara.okafor@carelink.ai",
    experience: "8 years",
    certifications: ["RN License", "BLS", "ACLS", "Pediatric Advanced Life Support"],
    languages: ["English", "Igbo", "Yoruba"],
    availability: "Immediate",
    status: "available",
    interviewDate: null,
    source: "Indeed",
    documents: [
      { name: "License", status: "verified" },
      { name: "Background Check", status: "verified" },
      { name: "References", status: "verified" },
    ],
  },
  {
    id: 2,
    name: "Kwame Mensah",
    role: "Physical Therapist",
    location: "Accra, Ghana",
    trustScore: 96,
    skills: ["Rehabilitation", "Sports Therapy", "Geriatric Care"],
    allergySafe: true,
    matchScore: 92,
    avatar: "/african-man-therapist.jpg",
    phone: "+233 24 567 8901",
    email: "kwame.mensah@carelink.ai",
    experience: "6 years",
    certifications: ["PT License", "Sports Therapy Cert", "Manual Therapy"],
    languages: ["English", "Twi", "French"],
    availability: "2 weeks notice",
    status: "available",
    interviewDate: null,
    source: "Scan123",
    documents: [
      { name: "License", status: "verified" },
      { name: "Background Check", status: "pending" },
      { name: "References", status: "verified" },
    ],
  },
  {
    id: 3,
    name: "Zainab Hassan",
    role: "Home Health Aide",
    location: "Nairobi, Kenya",
    trustScore: 94,
    skills: ["Personal Care", "Medication Management", "Companionship"],
    allergySafe: false,
    matchScore: 89,
    avatar: "/african-woman-caregiver.jpg",
    phone: "+254 712 345 678",
    email: "zainab.hassan@carelink.ai",
    experience: "5 years",
    certifications: ["HHA Certificate", "First Aid", "CPR"],
    languages: ["English", "Swahili", "Arabic"],
    availability: "Immediate",
    status: "available",
    interviewDate: null,
    source: "Wellsky",
    documents: [
      { name: "License", status: "verified" },
      { name: "Background Check", status: "verified" },
      { name: "References", status: "pending" },
    ],
  },
]

export const integrationWorkflowSteps: IntegrationWorkflowStep[] = [
  {
    id: 1,
    title: "Connect Platform",
    description: "Authenticate the job source and enable data sharing.",
  },
  {
    id: 2,
    title: "Configure Filters",
    description: "Apply guardrails that match your hiring priorities.",
  },
  {
    id: 3,
    title: "Preview Candidates",
    description: "Review matched caregivers before importing to your network.",
  },
  {
    id: 4,
    title: "Import to Network",
    description: "Approve caregivers and sync them into CareLink.",
  },
]

export const platformIntegrations: PlatformIntegration[] = [
  {
    platformId: 1,
    lastSync: "12 minutes ago",
    nextSync: "Scheduled for 6:00 PM",
    completionStep: 3,
    filters: [
      {
        id: "experience",
        label: "Experience ≥ 3 years",
        description: "Only surface caregivers with proven clinical experience.",
        type: "include",
        value: "3+ years",
      },
      {
        id: "certifications",
        label: "Required: RN License & BLS",
        description: "Ensure foundational credentials are in place.",
        type: "include",
        value: "RN, BLS",
      },
      {
        id: "availability",
        label: "Immediate availability",
        description: "Prioritize caregivers ready to deploy within 7 days.",
        type: "limit",
        value: "Within 7 days",
      },
    ],
    candidates: [
      {
        id: 101,
        name: "Lola Adebayo",
        role: "Registered Nurse",
        experience: "6 years",
        location: "Abuja, Nigeria",
        specialty: "Critical Care",
        availability: "Immediate",
        matchScore: 94,
        status: "Ready",
      },
      {
        id: 102,
        name: "Farida Bello",
        role: "Licensed Practical Nurse",
        experience: "4 years",
        location: "Kaduna, Nigeria",
        specialty: "Geriatric Care",
        availability: "Within 2 weeks",
        matchScore: 88,
        status: "Filtered",
      },
      {
        id: 103,
        name: "Samuel Ojo",
        role: "Home Health Aide",
        experience: "5 years",
        location: "Lagos, Nigeria",
        specialty: "Medication Management",
        availability: "Immediate",
        matchScore: 90,
        status: "Ready",
      },
      {
        id: 104,
        name: "Nneka Iwu",
        role: "Registered Nurse",
        experience: "7 years",
        location: "Port Harcourt, Nigeria",
        specialty: "Pediatrics",
        availability: "Within 1 week",
        matchScore: 92,
        status: "Imported",
      },
    ],
  },
  {
    platformId: 2,
    lastSync: "27 minutes ago",
    nextSync: "Auto-sync every 4 hours",
    completionStep: 2,
    filters: [
      {
        id: "language",
        label: "Bilingual caregivers",
        description: "Match communities needing English + local dialect fluency.",
        type: "include",
        value: "English + Twi",
      },
      {
        id: "travel",
        label: "Travel radius ≤ 20km",
        description: "Optimize for caregivers willing to travel short distances.",
        type: "limit",
        value: "≤ 20km",
      },
      {
        id: "certifications",
        label: "Advanced manual therapy",
        description: "Surface therapists with sports medicine expertise.",
        type: "include",
        value: "Manual Therapy, Sports Rehab",
      },
    ],
    candidates: [
      {
        id: 201,
        name: "Kojo Owusu",
        role: "Physical Therapist",
        experience: "5 years",
        location: "Accra, Ghana",
        specialty: "Sports Rehabilitation",
        availability: "Within 2 weeks",
        matchScore: 87,
        status: "Filtered",
      },
      {
        id: 202,
        name: "Adwoa Boateng",
        role: "Physiotherapy Assistant",
        experience: "3 years",
        location: "Tema, Ghana",
        specialty: "Geriatric Mobility",
        availability: "Immediate",
        matchScore: 82,
        status: "New",
      },
      {
        id: 203,
        name: "Yaw Mensah",
        role: "Occupational Therapist",
        experience: "6 years",
        location: "Kumasi, Ghana",
        specialty: "Neurological Rehab",
        availability: "Within 1 week",
        matchScore: 85,
        status: "Ready",
      },
    ],
  },
  {
    platformId: 3,
    lastSync: "45 minutes ago",
    nextSync: "Manual sync required",
    completionStep: 1,
    filters: [
      {
        id: "allergy",
        label: "Allergy-aware caregivers",
        description: "Ensure caregivers understand allergy-safe care plans.",
        type: "include",
        value: "Allergy-safe certified",
      },
      {
        id: "background",
        label: "Background checks verified",
        description: "Only surface caregivers with completed compliance docs.",
        type: "include",
        value: "Background check verified",
      },
    ],
    candidates: [
      {
        id: 301,
        name: "Amina Yusuf",
        role: "Home Health Aide",
        experience: "4 years",
        location: "Nairobi, Kenya",
        specialty: "Medication Administration",
        availability: "Immediate",
        matchScore: 89,
        status: "Filtered",
      },
      {
        id: 302,
        name: "Grace Wanjiru",
        role: "Personal Support Worker",
        experience: "3 years",
        location: "Mombasa, Kenya",
        specialty: "Companionship & ADL",
        availability: "Within 3 weeks",
        matchScore: 80,
        status: "New",
      },
      {
        id: 303,
        name: "Peter Otieno",
        role: "Certified Nursing Assistant",
        experience: "5 years",
        location: "Kisumu, Kenya",
        specialty: "Post-operative Care",
        availability: "Within 1 week",
        matchScore: 86,
        status: "Ready",
      },
    ],
  },
]
