// Comprehensive mock data for CareLink AI platform

export const recruiterData = {
  jobSources: [
    { id: 1, name: "Indeed", icon: "🔗", connected: true, applicants: 24 },
    { id: 2, name: "Scan123", icon: "🔗", connected: true, applicants: 18 },
    { id: 3, name: "Wellsky", icon: "🔗", connected: true, applicants: 12 },
  ],
  applicants: [
    {
      id: 1,
      name: "Amara Okafor",
      role: "Registered Nurse",
      location: "Lagos, Nigeria",
      trustScore: 98,
      skills: ["Pediatric Care", "Emergency Response", "Patient Education"],
      allergySafe: true,
      matchScore: 95,
      avatar: "/african-woman-nurse.jpg",
      phone: "+234 801 234 5678",
      email: "amara.okafor@carelink.ai",
      experience: "8 years",
      certifications: ["RN License", "BLS", "ACLS", "Pediatric Advanced Life Support"],
      languages: ["English", "Igbo", "Yoruba"],
      availability: "Immediate",
      status: "available" as const,
      interviewDate: null,
      source: "Indeed",
      documents: [
        { name: "License", status: "verified" },
        { name: "Background Check", status: "verified" },
        { name: "References", status: "verified" },
      ],
    },
    {
      id: 2,
      name: "Kwame Mensah",
      role: "Physical Therapist",
      location: "Accra, Ghana",
      trustScore: 96,
      skills: ["Rehabilitation", "Sports Therapy", "Geriatric Care"],
      allergySafe: true,
      matchScore: 92,
      avatar: "/african-man-therapist.jpg",
      phone: "+233 24 567 8901",
      email: "kwame.mensah@carelink.ai",
      experience: "6 years",
      certifications: ["PT License", "Sports Therapy Cert", "Manual Therapy"],
      languages: ["English", "Twi", "French"],
      availability: "2 weeks notice",
      status: "available" as const,
      interviewDate: null,
      source: "Scan123",
      documents: [
        { name: "License", status: "verified" },
        { name: "Background Check", status: "pending" },
        { name: "References", status: "verified" },
      ],
    },
    {
      id: 3,
      name: "Zainab Hassan",
      role: "Home Health Aide",
      location: "Nairobi, Kenya",
      trustScore: 94,
      skills: ["Personal Care", "Medication Management", "Companionship"],
      allergySafe: false,
      matchScore: 89,
      avatar: "/african-woman-caregiver.jpg",
      phone: "+254 712 345 678",
      email: "zainab.hassan@carelink.ai",
      experience: "5 years",
      certifications: ["HHA Certificate", "First Aid", "CPR"],
      languages: ["English", "Swahili", "Arabic"],
      availability: "Immediate",
      status: "available" as const,
      interviewDate: null,
      source: "Wellsky",
      documents: [
        { name: "License", status: "verified" },
        { name: "Background Check", status: "verified" },
        { name: "References", status: "pending" },
      ],
    },
  ],
}

export const caregiverData = {
  timeline: [
    {
      id: 1,
      status: "Placed",
      title: "Position Confirmed",
      description: "You have been placed at Sunrise Care Home",
      date: "Today, 2:30 PM",
      completed: true,
      details: "Start date: Next Monday. Orientation scheduled for 9:00 AM. Contact: Sarah Johnson, HR Manager.",
    },
    {
      id: 2,
      status: "Matched",
      title: "Client Match Found",
      description: "Matched with Sunrise Care Home - 95% compatibility",
      date: "Yesterday, 4:15 PM",
      completed: true,
      details: "Facility specializes in geriatric care. 50-bed facility with modern equipment. Team of 15 caregivers.",
    },
    {
      id: 3,
      status: "Screening",
      title: "Background Check Complete",
      description: "All verifications passed successfully",
      date: "2 days ago",
      completed: true,
      details: "Criminal background check, employment verification, and reference checks all cleared.",
    },
    {
      id: 4,
      status: "Applied",
      title: "Application Submitted",
      description: "Your profile was submitted for review",
      date: "5 days ago",
      completed: true,
      details: "Application reviewed by AI matching system and forwarded to 3 potential employers.",
    },
  ],
  documents: [
    {
      id: 1,
      name: "Nursing License",
      type: "Certification",
      status: "Verified",
      uploadDate: "Jan 15, 2025",
      expiryDate: "Jan 15, 2027",
      verifiedBy: "CareLink AI System",
      fileSize: "2.4 MB",
      qualityScore: 98,
      authenticityScore: 99,
      complianceStatus: "Compliant",
      aiNotes: "Document verified through OCR and database cross-reference. All security features present.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
    {
      id: 2,
      name: "CPR Certification",
      type: "Certification",
      status: "Verified",
      uploadDate: "Dec 10, 2024",
      expiryDate: "Dec 10, 2026",
      verifiedBy: "Red Cross",
      fileSize: "1.8 MB",
      qualityScore: 96,
      authenticityScore: 98,
      complianceStatus: "Compliant",
      aiNotes: "Valid Red Cross certification. Expiry date within acceptable range.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
    {
      id: 3,
      name: "Background Check",
      type: "Legal",
      status: "Verified",
      uploadDate: "Jan 5, 2025",
      expiryDate: "Jan 5, 2026",
      verifiedBy: "National Bureau",
      fileSize: "856 KB",
      qualityScore: 94,
      authenticityScore: 97,
      complianceStatus: "Compliant",
      aiNotes: "Background check clear. No red flags detected.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
    {
      id: 4,
      name: "TB Test Results",
      type: "Medical",
      status: "Verified",
      uploadDate: "Jan 8, 2025",
      expiryDate: "Jan 8, 2026",
      verifiedBy: "City Health Clinic",
      fileSize: "1.2 MB",
      qualityScore: 92,
      authenticityScore: 96,
      complianceStatus: "Compliant",
      aiNotes: "TB test negative. Medical document authenticated.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
    {
      id: 5,
      name: "Hepatitis B Vaccination",
      type: "Medical",
      status: "Verified",
      uploadDate: "Nov 20, 2024",
      expiryDate: "Lifetime",
      verifiedBy: "City Health Clinic",
      fileSize: "945 KB",
      qualityScore: 95,
      authenticityScore: 99,
      complianceStatus: "Compliant",
      aiNotes: "Vaccination record verified. Lifetime immunity confirmed.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
    {
      id: 6,
      name: "Professional References",
      type: "Reference",
      status: "Verified",
      uploadDate: "Jan 3, 2025",
      expiryDate: "N/A",
      verifiedBy: "3 References Contacted",
      fileSize: "654 KB",
      qualityScore: 91,
      authenticityScore: 95,
      complianceStatus: "Compliant",
      aiNotes: "All 3 references verified. Positive feedback received.",
      riskLevel: "Low",
      recommendedAction: "Approved",
    },
  ],
  matchedClients: [
    {
      id: 1,
      name: "Sunrise Care Home",
      type: "Facility",
      trustScore: 95,
      matchScore: 95,
      location: "Lagos, Nigeria",
      specialization: "Geriatric Care",
      status: "matched",
      image: "/care-facility.jpg",
    },
    {
      id: 2,
      name: "Mrs. Adeyemi",
      type: "Individual",
      trustScore: 92,
      matchScore: 88,
      location: "Ikoyi, Lagos",
      specialization: "Post-Surgery Care",
      status: "matched",
      image: "/elderly-woman.png",
    },
    {
      id: 3,
      name: "Wellness Center",
      type: "Facility",
      trustScore: 89,
      matchScore: 85,
      location: "Victoria Island, Lagos",
      specialization: "Rehabilitation",
      status: "rejected",
      image: "/wellness-center.jpg",
    },
  ],
}

export const clientData = {
  matchedCaregivers: [
    {
      id: 1,
      name: "Amara Okafor",
      role: "Registered Nurse",
      location: "Lagos, Nigeria",
      trustScore: 98,
      matchScore: 95,
      skills: ["Pediatric Care", "Emergency Response", "Patient Education"],
      avatar: "/african-woman-nurse.jpg",
      experience: "8 years",
      availability: "Immediate",
      status: "matched",
    },
    {
      id: 2,
      name: "Kwame Mensah",
      role: "Physical Therapist",
      location: "Accra, Ghana",
      trustScore: 96,
      matchScore: 92,
      skills: ["Rehabilitation", "Sports Therapy", "Geriatric Care"],
      avatar: "/african-man-therapist.jpg",
      experience: "6 years",
      availability: "2 weeks notice",
      status: "matched",
    },
    {
      id: 3,
      name: "Zainab Hassan",
      role: "Home Health Aide",
      location: "Nairobi, Kenya",
      trustScore: 94,
      matchScore: 89,
      skills: ["Personal Care", "Medication Management", "Companionship"],
      avatar: "/african-woman-caregiver.jpg",
      experience: "5 years",
      availability: "Immediate",
      status: "matched",
    },
  ],
  schedules: [
    {
      id: 1,
      caregiver: "Amara Okafor",
      date: "Monday, Jan 20",
      time: "6:00 AM - 2:00 PM",
      type: "Morning Shift",
      status: "confirmed",
    },
    {
      id: 2,
      caregiver: "Kwame Mensah",
      date: "Tuesday, Jan 21",
      time: "2:00 PM - 10:00 PM",
      type: "Afternoon Shift",
      status: "confirmed",
    },
    {
      id: 3,
      caregiver: "Zainab Hassan",
      date: "Wednesday, Jan 22",
      time: "10:00 PM - 6:00 AM",
      type: "Night Shift",
      status: "pending",
    },
  ],
  matchingAnalysis: [
    {
      id: 1,
      caregiver: "Amara Okafor",
      matchScore: 95,
      trustScore: 98,
      compatibilityFactors: [
        { factor: "Skills Match", score: 98, weight: "High" },
        { factor: "Experience Level", score: 96, weight: "High" },
        { factor: "Location Proximity", score: 92, weight: "Medium" },
        { factor: "Availability", score: 100, weight: "High" },
        { factor: "Communication Style", score: 94, weight: "Medium" },
        { factor: "Care Philosophy", score: 93, weight: "High" },
      ],
      aiInsights:
        "Excellent match based on your care requirements. Amara has extensive pediatric care experience and immediate availability. Her communication style aligns well with your preferences.",
      riskFactors: [],
      recommendedAction: "Highly Recommended",
    },
    {
      id: 2,
      caregiver: "Kwame Mensah",
      matchScore: 92,
      trustScore: 96,
      compatibilityFactors: [
        { factor: "Skills Match", score: 94, weight: "High" },
        { factor: "Experience Level", score: 92, weight: "High" },
        { factor: "Location Proximity", score: 85, weight: "Medium" },
        { factor: "Availability", score: 88, weight: "High" },
        { factor: "Communication Style", score: 91, weight: "Medium" },
        { factor: "Care Philosophy", score: 90, weight: "High" },
      ],
      aiInsights:
        "Strong match for rehabilitation and geriatric care needs. Kwame requires 2 weeks notice but has proven expertise in your care type.",
      riskFactors: ["Availability requires advance notice"],
      recommendedAction: "Recommended",
    },
    {
      id: 3,
      caregiver: "Zainab Hassan",
      matchScore: 89,
      trustScore: 94,
      compatibilityFactors: [
        { factor: "Skills Match", score: 88, weight: "High" },
        { factor: "Experience Level", score: 90, weight: "High" },
        { factor: "Location Proximity", score: 87, weight: "Medium" },
        { factor: "Availability", score: 100, weight: "High" },
        { factor: "Communication Style", score: 89, weight: "Medium" },
        { factor: "Care Philosophy", score: 85, weight: "High" },
      ],
      aiInsights:
        "Good match for personal care and companionship. Zainab has immediate availability and strong patient feedback.",
      riskFactors: [],
      recommendedAction: "Recommended",
    },
  ],
}
